language: python
os: liunx
python:  
  - '3.5'
  - '3.6'
before_install: 
  - pip install --upgrade pyflakes
  - pip install flask
script:
  - pyflakes function_table.py
  - pyflakes main.py
  - python main.py
